name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Stage 1: Setup (instalação das dependências)
  setup:
    name: Setup - Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das dependências do Projeto
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
          tar -zxvf allure-2.13.8.tgz
          sudo mv allure-2.13.8 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

  # Stage 2: Testes (executando testes de API)
  test_api:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: setup  # Este job depende do job 'setup' ser concluído

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Robot Framework tests
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
        run: |
          echo Executando os testes de API do Robot
          robot -d logs --listener allure_robotframework ./tests/ || true

      - name: Generate Allure Report
        run: |
          allure generate output/allure -o allure-report --clean
    
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: allure-report/

  # Stage 3: Deploy (fazendo o deploy do relatório)
  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
      - test_api  # Executa após o job de testes ser concluído

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://marilliadantas.github.io/api-test-robot/index.html

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report-api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Publicando o relatório baixado

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4